# Site settings
title: 情報リテラシー基礎
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/premium' # the subpath of your site, e.g. /blog/
url: 'https://infolit.uec.tmu.ac.jp' # the base hostname & protocol for your site
screenshot_dir: './pic'
screencast_dir: './mov'

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - 'no_intra_emphasis'
    - 'fenced_code_blocks'
    - 'space_after_headers'
    - 'tables'
    - 'with_toc_data'
exclude:
  - 'Rakefile'
  - 'README.md'
  - 'config.rb'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'vendor'
